name: ExplosiveSnowballs
main: IceCruelStuff\ExplosiveSnowballs\ExplosiveSnowballs
api: 3.14.0
version: 1.0.1
author: IceCruelStuff

commands:
  snowballs:
    description: "Manages ExplosiveSnowballs plugin"
    usage: "/snowballs <args>"
    permission: snowballs.command

permission:
  snowballs.command:
    default: op
    description: "Permission for ExplosiveSnowballs plugin"
